variable "project" {
  type        = string
  description = "The ID of the project in which the resource belongs"
}

variable "gateway_config" {
  type        = string
  description = "Google Cloud IAM service account used to sign OIDC tokens for backends that have authentication configured."
  default     = null
}

variable "openapi_documents" {
  type = object({
    path     = string
    contents = string
  })
  default     = {}
  description = "The OpenAPI Specification document file with the path of the file and its content encoded in base64."
}

variable "grpc_services" {
  type = object({
    file_descriptor_set = object({
      contents = string
      path     = string
    })
    source = optional(object({
      contents = string
      path     = string
    }))
  })
  default     = {}
  description = "File descriptor set : generated by protoc. To generate, use protoc with imports and source info included, source: Uncompiled proto files associated with the descriptor set, used for display purposes."
}

variable "api_gateway" {
  type = map(object({}))
}

variable "members" {
  type    = list(string)
  default = []
}

variable "region" {
  type        = string
  default     = null
  description = "Region of the gateway for the API"
}