resource "aci_ldap_provider" "ldap_provider" {
  count                           = length(var.ldap_provider)
  name                            = lookup(var.ldap_provider[count.index], "name")
  type                            = lookup(var.ldap_provider[count.index], "type")
  description                     = lookup(var.ldap_provider[count.index], "description", null)
  annotation                      = lookup(var.ldap_provider[count.index], "annotation", null)
  name_alias                      = lookup(var.ldap_provider[count.index], "name_alias", null)
  ssl_validation_level            = lookup(var.ldap_provider[count.index], "ssl_validation_level", null)
  attribute                       = lookup(var.ldap_provider[count.index], "attribute", null)
  basedn                          = lookup(var.ldap_provider[count.index], "basedn", null)
  enable_ssl                      = lookup(var.ldap_provider[count.index], "enable_ssl", null)
  filter                          = lookup(var.ldap_provider[count.index], "filter", null)
  key                             = lookup(var.ldap_provider[count.index], "key", null)
  monitor_server                  = lookup(var.ldap_provider[count.index], "monitor_server", null)
  monitoring_password             = lookup(var.ldap_provider[count.index], "monitoring_password", null)
  monitoring_user                 = lookup(var.ldap_provider[count.index], "monitoring_user", null)
  port                            = lookup(var.ldap_provider[count.index], "port", null)
  retries                         = lookup(var.ldap_provider[count.index], "retries", null)
  rootdn                          = lookup(var.ldap_provider[count.index], "rootdn", null)
  timeout                         = lookup(var.ldap_provider[count.index], "timeout", null)
  relation_aaa_rs_prov_to_epp     = lookup(var.ldap_provider[count.index], "relation_aaa_rs_prov_to_epp", null)
  relation_aaa_rs_sec_prov_to_epg = lookup(var.ldap_provider[count.index], "relation_aaa_rs_sec_prov_to_epg", null)
}