variable "tags" {
  type    = map(string)
  default = {}
}

variable "access_point" {
  type = list(map(object({
    id             = number
    file_system_id = number
    tags           = optional(map(string))
    posix_user = optional(list(object({
      gid            = number
      uid            = number
      secondary_gids = optional(list(string))
    })), [])
    root_directory = optional(list(object({
      path = optional(string)
      creation_info = optional(list(object({
        owner_gid   = number
        owner_uid   = number
        permissions = string
      })), [])
    })), [])
  })))
  default     = []
  description = <<EOF
This resource supports the following arguments:
file_system_id - (Required) ID of the file system for which the access point is intended.
posix_user - (Optional) Operating system user and group applied to all file system requests made using the access point. Detailed below.
root_directory- (Optional) Directory on the Amazon EFS file system that the access point provides access to. Detailed below.
tags - (Optional) Key-value mapping of resource tags. If configured with a provider default_tags configuration block present, tags with matching keys will overwrite those defined at the provider-level.

posix_user
gid - (Required) POSIX group ID used for all file system operations using this access point.
secondary_gids - (Optional) Secondary POSIX group IDs used for all file system operations using this access point.
uid - (Required) POSIX user ID used for all file system operations using this access point.

root_directory
The access point exposes the specified file system path as the root directory of your file system to applications using the access point. NFS clients using the access point can only access data in the access point's RootDirectory and it's subdirectories.
creation_info - (Optional) POSIX IDs and permissions to apply to the access point's Root Directory. See Creation Info below.
path - (Optional) Path on the EFS file system to expose as the root directory to NFS clients using the access point to access the EFS file system. A path can have up to four subdirectories. If the specified path does not exist, you are required to provide creation_info.

creation_info
If the path specified does not exist, EFS creates the root directory using the creation_info settings when a client connects to an access point.
owner_gid - (Required) POSIX group ID to apply to the root_directory.
owner_uid - (Required) POSIX user ID to apply to the root_directory.
permissions - (Required) POSIX permissions to apply to the RootDirectory, in the format of an octal number representing the file's mode bits.
  EOF
}

variable "backup_policy" {
  type = list(map(object({
    id             = number
    file_system_id = number
    backup_policy = list(object({
      status = string
    }))
  })))
  default     = []
  description = <<EOF
This resource supports the following arguments:
file_system_id - (Required) The ID of the EFS file system.
backup_policy - (Required) A backup_policy object (documented below).

Backup Policy Arguments
backup_policy supports the following arguments:
status - (Required) A status of the backup policy. Valid values: ENABLED, DISABLED.
  EOF
}

variable "file_system" {
  type = list(map(object({
    id                              = number
    availability_zone_name          = optional(string)
    creation_token                  = optional(string)
    encrypted                       = optional(bool)
    kms_key_id                      = optional(string)
    performance_mode                = optional(string)
    provisioned_throughput_in_mibps = optional(number)
    tags                            = optional(map(string))
    throughput_mode                 = optional(string)
    lifecycle_policy = optional(list(object({
      transition_to_archive               = optional(string)
      transition_to_ia                    = optional(string)
      transition_to_primary_storage_class = optional(string)
    })), [])
    protection = optional(list(object({
      replication_overwrite = optional(string)
    })), [])
  })))
  default     = []
  description = <<EOF
This resource supports the following arguments:
availability_zone_name - (Optional) the AWS Availability Zone in which to create the file system. Used to create a file system that uses One Zone storage classes. See user guide for more information.
creation_token - (Optional) A unique name (a maximum of 64 characters are allowed) used as reference when creating the Elastic File System to ensure idempotent file system creation. By default generated by Terraform. See Elastic File System user guide for more information.
encrypted - (Optional) If true, the disk will be encrypted.
kms_key_id - (Optional) The ARN for the KMS encryption key. When specifying kms_key_id, encrypted needs to be set to true.
lifecycle_policy - (Optional) A file system lifecycle policy object. See lifecycle_policy block below for details.
protection - (Optional) A file system protection object. See protection block below for details.
performance_mode - (Optional) The file system performance mode. Can be either "generalPurpose" or "maxIO" (Default: "generalPurpose").
provisioned_throughput_in_mibps - (Optional) The throughput, measured in MiB/s, that you want to provision for the file system. Only applicable with throughput_mode set to provisioned.
tags - (Optional) A map of tags to assign to the file system. If configured with a provider default_tags configuration block present, tags with matching keys will overwrite those defined at the provider-level.
throughput_mode - (Optional) Throughput mode for the file system. Defaults to bursting. Valid values: bursting, provisioned, or elastic. When using provisioned, also set provisioned_throughput_in_mibps.

lifecycle_policy Block
Describes a policy used by Lifecycle management that specifies when to transition files into and out of storage classes. For more information, see Managing file system storage.
The lifecycle_policy block supports the following arguments:
transition_to_archive - (Optional) Indicates how long it takes to transition files to the archive storage class. Requires transition_to_ia, Elastic Throughput and General Purpose performance mode. Valid values: AFTER_1_DAY, AFTER_7_DAYS, AFTER_14_DAYS, AFTER_30_DAYS, AFTER_60_DAYS, AFTER_90_DAYS, AFTER_180_DAYS, AFTER_270_DAYS, or AFTER_365_DAYS.
transition_to_ia - (Optional) Indicates how long it takes to transition files to the IA storage class. Valid values: AFTER_1_DAY, AFTER_7_DAYS, AFTER_14_DAYS, AFTER_30_DAYS, AFTER_60_DAYS, AFTER_90_DAYS, AFTER_180_DAYS, AFTER_270_DAYS, or AFTER_365_DAYS.
transition_to_primary_storage_class - (Optional) Describes the policy used to transition a file from infequent access storage to primary storage. Valid values: AFTER_1_ACCESS.

protection Block
Describes the protection on a file system.
The protection block supports the following arguments:
replication_overwrite - (Optional) Indicates whether replication overwrite protection is enabled. Valid values: ENABLED or DISABLED.
  EOF
}

variable "file_system_policy" {
  type = list(map(object({
    id                                 = number
    file_system_id                     = number
    policy                             = string
    bypass_policy_lockout_safety_check = optional(bool)
  })))
  default     = []
  description = <<EOF
  The following arguments are required:
file_system_id - (Required) The ID of the EFS file system.
policy - (Required) The JSON formatted file system policy for the EFS file system. see Docs for more info.

The following arguments are optional:
bypass_policy_lockout_safety_check - (Optional) A flag to indicate whether to bypass the aws_efs_file_system_policy lockout safety check. The policy lockout safety check determines whether the policy in the request will prevent the principal making the request will be locked out from making future PutFileSystemPolicy requests on the file system. Set bypass_policy_lockout_safety_check to true only when you intend to prevent the principal that is making the request from making a subsequent PutFileSystemPolicy request on the file system. The default value is false.
  EOF
}

variable "mount_target" {
  type = list(map(object({
    id              = number
    file_system_id  = number
    subnet_id       = string
    ip_address      = optional(string)
    security_groups = optional(list(string))
  })))
  default     = []
  description = <<EOF
This resource supports the following arguments:
file_system_id - (Required) The ID of the file system for which the mount target is intended.
subnet_id - (Required) The ID of the subnet to add the mount target in.
ip_address - (Optional) The address (within the address range of the specified subnet) at which the file system may be mounted via the mount target.
security_groups - (Optional) A list of up to 5 VPC security group IDs (that must be for the same VPC as subnet specified) in effect for the mount target.
  EOF
}

variable "replication_configuration" {
  type = list(map(object({
    id = number
    source_file_system_id = string
    destination = list(object({
      availability_zone_name = string
      file_system_id = string
      kms_key_id = string
      region = string
      }))
  })))
  default     = []
  description = <<EOF
  EOF
}
